import type { DishConfig } from './types';

export const chickenRice: DishConfig = {
  id: 'chicken-rice',
  palette: {
    wall: '#60cfd2',
    wallDark: '#176f7f',
    floor: '#f4da94',
    tileLine: '#d2a253',
    counter: '#e8725e',
    counterTop: '#4fb9ab',
    counterDark: '#195963',
    accentTop: '#ffd565',
    accentBottom: '#f47d55',
    pendantWarm: '#ffe58b',
    pendantRing: '#f08a48',
  },
  stations: [
    { id: 'fridge', name: 'Fridge', shortName: 'Fridge', x: -3.15, z: -1.25, uiX: 18, uiY: 34 },
    { id: 'pantry', name: 'Rice Pantry', shortName: 'Pantry', x: -1.6, z: -2.0, uiX: 34, uiY: 26 },
    { id: 'board', name: 'Cutting Board', shortName: 'Board', x: 0.05, z: -2.0, uiX: 50, uiY: 26 },
    { id: 'riceCooker', name: 'Rice Cooker', shortName: 'Rice', x: 1.75, z: -2.0, uiX: 68, uiY: 26 },
    { id: 'pot', name: 'Stock Pot', shortName: 'Pot', x: 3.35, z: -0.35, uiX: 82, uiY: 45 },
    { id: 'mortar', name: 'Chili Mortar', shortName: 'Sauce', x: -2.4, z: 1.55, uiX: 27, uiY: 67 },
    { id: 'plate', name: 'Plate Station', shortName: 'Plate', x: -0.15, z: 1.38, uiX: 50, uiY: 67 },
    { id: 'serve', name: 'Serve Window', shortName: 'Serve', x: 1.75, z: 1.38, uiX: 70, uiY: 67 },
    { id: 'trash', name: 'Trash Bin', shortName: 'Trash', x: -3.3, z: 0.65, uiX: 15, uiY: 57 },
  ],
  collisionBoxes: [
    { minX: -3.35, maxX: 2.85, minZ: -2.52, maxZ: -1.56 },
    { minX: -2.98, maxX: 2.62, minZ: 1.05, maxZ: 1.78 },
    { minX: -3.78, maxX: -3.02, minZ: -1.34, maxZ: 1.36 },
    { minX: 2.92, maxX: 3.72, minZ: -1.04, maxZ: 1.58 },
  ],
  strings: {
    en: {
      name: 'Hainanese Chicken Rice',
      shortName: 'Chicken Rice',
      goal: 'Cook rice, poach chicken, pound chili, plate the set, and serve it hot.',
      itemLabels: {
        rawRice: 'Uncooked rice',
        cookingRice: 'Cooking rice',
        cookedRice: 'Fragrant rice',
        overcookedRice: 'Dry rice',
        rawChicken: 'Raw chicken',
        cutChicken: 'Cut chicken',
        poachingChicken: 'Poaching chicken',
        poachedChicken: 'Poached chicken',
        overcookedChicken: 'Tough chicken',
        chiliIngredients: 'Chili ingredients',
        chiliSauce: 'Chili sauce',
        chickenRice: 'Chicken rice',
      },
      plateLabels: { rice: 'Rice', chicken: 'Chicken', sauce: 'Chili' },
      workflowLabels: { rice: 'Rice', chicken: 'Chicken', sauce: 'Chili', plate: 'Plate', serve: 'Serve' },
      stationTips: {
        pantry: { title: 'Rice prep', body: 'Jasmine rice is rinsed first so the grains cook fluffy instead of gummy.' },
        riceCooker: { title: 'Fragrant rice', body: 'Garlic, ginger, chicken fat, stock, and pandan give the rice its savory aroma.' },
        fridge: { title: 'Chicken choice', body: 'A skin-on whole chicken gives juicy meat and a rich stock for the rice.' },
        board: { title: 'Prep the chicken', body: 'Trimming extra fat is useful: it can be rendered to perfume the rice.' },
        pot: { title: 'Poaching', body: 'Gentle poaching keeps the meat tender; an ice bath helps firm the skin.' },
        mortar: { title: 'Chili sauce', body: 'The sauce is pounded from red chili, garlic, ginger, lime or calamansi, and a splash of stock.' },
        plate: { title: 'Plating', body: 'Cucumber cools the plate, while chili and dark soy add heat and depth.' },
        serve: { title: 'Hawker classic', body: 'Singapore versions grew from Hainanese Wenchang chicken and local hawker practice.' },
      },
      startFeedback: 'Get rice from the pantry or chicken from the fridge.',
    },
    ja: {
      name: '海南風チキンライス',
      shortName: 'チキンライス',
      goal: 'お米を炊き、鶏肉を茹で、チリソースを潰し、盛り付けて熱々を出そう。',
      itemLabels: {
        rawRice: '生米',
        cookingRice: '炊飯中',
        cookedRice: '香り米',
        overcookedRice: '焦げ米',
        rawChicken: '生鶏肉',
        cutChicken: '切った鶏肉',
        poachingChicken: '湯通し中',
        poachedChicken: '茹で鶏',
        overcookedChicken: '硬い鶏肉',
        chiliIngredients: 'チリ材料',
        chiliSauce: 'チリソース',
        chickenRice: 'チキンライス',
      },
      plateLabels: { rice: 'ご飯', chicken: '鶏肉', sauce: 'チリ' },
      workflowLabels: { rice: 'ご飯', chicken: '鶏肉', sauce: 'チリ', plate: '盛付', serve: '提供' },
      stationTips: {
        pantry: { title: '米の準備', body: '炊く前に米を研ぐと、ふっくら炊き上がる。' },
        riceCooker: { title: '香り米', body: 'ニンニク、生姜、鶏脂、出汁、パンダンの葉で香りを出す。' },
        fridge: { title: '鶏肉選び', body: '皮付き丸鶏なら、肉はジューシーで出汁もコク深い。' },
        board: { title: '下処理', body: '余分な脂を切り落とすと、米を炊くときの香り付けに使える。' },
        pot: { title: '湯通し', body: '弱火でゆっくり湯通しすると柔らかく、氷水で皮が締まる。' },
        mortar: { title: 'チリソース', body: '赤唐辛子、ニンニク、生姜、ライム、出汁を一緒に潰す。' },
        plate: { title: '盛り付け', body: 'きゅうりが涼しさを、チリと黒醤油が辛味と深みを足す。' },
        serve: { title: '屋台の定番', body: 'シンガポール式は海南文昌鶏と屋台文化から生まれた。' },
      },
      startFeedback: 'パントリーから米、または冷蔵庫から鶏肉を取ろう。',
    },
  },
};
